name: Build Virtualbox

on: [push, pull_request]

jobs:
  build-virtualbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install virtualbox
        run: sudo apt-get install -y virtualbox 
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest" 
      - name: Run `packer init`
        id: init
        run: packer init virtualbox.pkr.hcl
      - name: Run `packer validate`
        id: validate
        run: packer init virtualbox.pkr.hcl
      - name: Run `packer build`
        id: build
        run: packer build virtualbox.pkg.hcl

