name: Build Virtualbox

on: [push, pull_request]

jobs:
  build-virtualbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install virtualbox
        run: |
          wget -q https://download.virtualbox.org/virtualbox/7.0.6/virtualbox-7.0_7.0.6-155176~Ubuntu~jammy_amd64.deb
          sudo apt-get update
          sudo apt-get install -y libqt5dbus5 libqt5gui5 libqt5help5 libqt5opengl5 libqt5printsupport5 libqt5widgets5 libqt5x11extras5 libqt5xml5 libvpx7
          sudo dpkg -i virtualbox-7.0_7.0.6-155176~Ubuntu~jammy_amd64.deb

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest" 
      - name: Run `packer init`
        id: init
        run: packer init virtualbox.pkr.hcl
      - name: Run `packer validate`
        id: validate
        run: packer init virtualbox.pkr.hcl
      - name: Run `packer build`
        id: build
        run: packer build virtualbox.pkr.hcl

